export const pets = [
  {
    id: 4,
    size: "Regular",
    name: "Jhontu",
    Description: "A highly energetic German Shepherd puppy with a strong build and a keen sense of alertness. Loves running and playing fetch.",
    gender: "Male",
    sterilized: false,
    age: "6 months",
    breed: "German Shepherd",
    medical_history: {
      rabies: true,
      flu: false,
      dewormed: true,
    },
    further_medical_history: "Recently completed first round of vaccinations and health check-ups.",
    weight: 12,
    imageUrl: "https://res.cloudinary.com/dr6pjobzl/image/upload/v1742402844/911P5ZgJmLL._AC_UF894_1000_QL80__bqiuus.jpg",
    type: "Dog",
  },
  {
    id: 2,
    size: "Smol",
    name: "Mishti",
    Description: "A playful Scottish Fold kitten with adorable folded ears. Very curious and loves chasing toys around the house.",
    gender: "Male",
    sterilized: false,
    age: "4 months",
    breed: "Scottish Fold",
    medical_history: {
      rabies: false,
      flu: true,
      dewormed: true,
    },
    further_medical_history: "Mild flu when younger, but now in good health.",
    weight: 2.2,
    imageUrl: "https://res.cloudinary.com/dr6pjobzl/image/upload/v1742402843/vsze5rkvcmt71_unt8ak.webp",
    type: "Cat",
  },
  {
    id: 5,
    size: "Regular",
    name: "Kaju",
    Description: "A vibrant blue-and-yellow Macaw with a playful and talkative nature. Loves mimicking sounds and interacting with people.",
    gender: "Female",
    sterilized: false,
    age: "1 year",
    breed: "Macaw",
    medical_history: {
      rabies: false,
      flu: true,
      dewormed: false,
    },
    further_medical_history: "Had mild respiratory issues a few months ago, but has recovered.",
    weight: 1.2,
    imageUrl: "https://res.cloudinary.com/dr6pjobzl/image/upload/v1742402843/2018-08-07_animal_hyacinth-macaw_center-center_001_nvug2b.webp",
    type: "Bird",
  },
  {
    id: 1,
    size: "Long potat",
    name: "Minty",
    Description: "A fluffy Persian cat with a luxurious white coat and bright blue eyes. Loves lounging in the sun and being pampered.",
    gender: "Male",
    sterilized: true,
    age: "3 years",
    breed: "Persian",
    medical_history: {
      rabies: true,
      flu: false,
      dewormed: true,
    },
    further_medical_history: "Had a minor eye infection last year but fully recovered.",
    weight: 4.5,
    imageUrl: "https://res.cloudinary.com/dr6pjobzl/image/upload/v1742402844/persian-cat_aq0yhg.jpg",
    type: "Cat",
  },
  {
    id: 6,
    size: "Regular",
    name: "Hena",
    Description: "A fluffy, black-and-white rabbit with a gentle and curious nature. Loves nibbling on fresh veggies and hopping around the garden.",
    gender: "Female",
    sterilized: false,
    age: "1 year",
    breed: "Rabbit",
    medical_history: {
      rabies: false,
      flu: false,
      dewormed: true,
    },
    further_medical_history: "Had minor ear mites issue but was successfully treated.",
    weight: 2.5,
    imageUrl: "https://res.cloudinary.com/dr6pjobzl/image/upload/v1742402845/Rabbit-Facts_e0snas.webp",
    type: "Rabbit",
  },
  {
    id: 3,
    size: "Chonky",
    name: "Lalu",
    Description: "A tiny Persian kitten with a fluffy golden coat. Loves cuddling and sleeping in warm spots.",
    gender: "Male",
    sterilized: false,
    age: "5 months",
    breed: "Orange",
    medical_history: {
      rabies: false,
      flu: false,
      dewormed: true,
    },
    further_medical_history: "Had mild digestive issues but recovered after diet adjustment.",
    weight: 1.8,
    imageUrl: "https://res.cloudinary.com/dr6pjobzl/image/upload/v1742402843/breed-spotlight-scottish-fold-min_cvquwn.webp",
    type: "Cat",
  }
];